# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HDlm265kUgrPfXx0uFwfcYLYn_oFnK1o
"""

a = int(input())
b = int(input())
print(a//b)
print(a/b)